name: Test Go x64 on M1

on: [workflow_dispatch]

jobs:
  test-go-x64:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - run: go version
      - run: arch -x86_64 go version
      - run: |
          echo 'package main; import "fmt"; func main() { fmt.Println("Hello from x64-Go!") }' > hello.go
          arch -x86_64 go run hello.go