name: Dotnet Test x64 .NET SDK on Apple Silicon

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  test-x64-dotnet:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Setup x64 .NET SDK
        uses: lmvysakh/setup-dotnet@FR_524_arch_support
        with:
          dotnet-version: '8.0.416'
          architecture: 'arm64'

      - name: Ensure DOTNET_ROOT_X64 is set
        run: |
          echo "DOTNET_ROOT_X64 before export: $DOTNET_ROOT_X64"
          if [ -z "$DOTNET_ROOT_X64" ]; then
            export DOTNET_ROOT_X64=$(dirname $(which dotnet))
            echo "DOTNET_ROOT_X64 was not set, setting to: $DOTNET_ROOT_X64"
          fi
          echo "DOTNET_ROOT_X64: $DOTNET_ROOT_X64"
          echo "DOTNET_ROOT_X64=$(dirname $(which dotnet))" >> $GITHUB_ENV

      - name: Show .NET x64 SDK details
        run: |
          echo "DOTNET_ROOT_X64: $DOTNET_ROOT_X64"
          "$DOTNET_ROOT_X64/dotnet" --info

      - name: Create sample project
        run: |
          "$DOTNET_ROOT_X64/dotnet" new console -o HelloX64
          cd HelloX64
          "$DOTNET_ROOT_X64/dotnet" build

      - name: Run sample project (x64)
        run: |
          cd HelloX64
          "$DOTNET_ROOT_X64/dotnet" run 