name: Dotnet checking with PR

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-pr:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Setup x64 .NET SDK
        uses: lmvysakh/setup-dotnet@FR_524_arch_support
        with:
          dotnet-version:  | 
            version: 8.0.x, arch: x64
            version: 8.0.x, arch: arm64

     
      - name: Show installed dotnet SDKs 
        run: |
          dotnet --list-sdks
          dotnet --info

      - name: Ensure DOTNET_ROOT_ARM64 is set
        run: |
          echo "DOTNET_ROOT_ARM64 before export: $DOTNET_ROOT_ARM64"
          if [ -z "$DOTNET_ROOT_ARM64" ]; then
            export DOTNET_ROOT_ARM64=$(dirname $(which dotnet))
            echo "DOTNET_ROOT_ARM64 was not set, setting to: $DOTNET_ROOT_ARM64"
          fi
          echo "DOTNET_ROOT_ARM64: $DOTNET_ROOT_ARM64"
          echo "DOTNET_ROOT_ARM64=$(dirname $(which dotnet))" >> $GITHUB_ENV

      - name: Show arm64 .NET SDK and info
        run: |
          echo "DOTNET_ROOT_ARM64: $DOTNET_ROOT_ARM64"
          "$DOTNET_ROOT_ARM64/dotnet" --list-sdks
          "$DOTNET_ROOT_ARM64/dotnet" --info

      - name: Ensure DOTNET_ROOT_X64 is set
        run: |
          echo "DOTNET_ROOT_X64 before export: $DOTNET_ROOT_X64"
          if [ -z "$DOTNET_ROOT_X64" ]; then
            export DOTNET_ROOT_X64=$(dirname $(which dotnet))
            echo "DOTNET_ROOT_X64 was not set, setting to: $DOTNET_ROOT_X64"
          fi
          echo "DOTNET_ROOT_X64: $DOTNET_ROOT_X64"
          echo "DOTNET_ROOT_X64=$(dirname $(which dotnet))" >> $GITHUB_ENV

      - name: Show x64 .NET SDK and info
        run: |
          echo "DOTNET_ROOT_X64: $DOTNET_ROOT_X64"
          "$DOTNET_ROOT_X64/dotnet" --list-sdks
          "$DOTNET_ROOT_X64/dotnet" --info

      - name: Inspect dotnet binary architectures
        run: |
          file "$DOTNET_ROOT_X64/dotnet"
          file "$DOTNET_ROOT_ARM64/dotnet"

      # - name: Show .NET x64 SDK and info (under Rosetta/x64)
      #   run: |
      #     echo "DOTNET_ROOT_X64: $DOTNET_ROOT_X64"
      #     arch -x86_64 "$DOTNET_ROOT_X64/dotnet" --list-sdks
      #     arch -x86_64 "$DOTNET_ROOT_X64/dotnet" --info