name: Feature implementation testing

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-feature:
    strategy:
        matrix:
        arch: [x64, arm64]
        runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: lmvysakh/setup-dotnet@FR_524_arch_support
        with:
          dotnet-version: '8.0.416'
          architecture: ${{ matrix.arch }}


      - name: Show installed dotnet SDKs 
        run: |
          dotnet --list-sdks
          dotnet --info



 