name: Testing Feature implementation with PR 338 and Internal PR

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-feature:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: DataDog/setup-dotnet@architecture2
        with:
          dotnet-version: '8.0.x'
          architecture: x86

      - name: Show installed dotnet SDKs 
        run: |
          dotnet --list-sdks
          dotnet --info



 