name: Testing Feature implementation with PR 338 and Internal PR

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-feature:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: lmvysakh/setup-dotnet@FR_524_arch_support
        env:
        PROCESSOR_ARCHITECTURE: x86
        DOTNET_INSTALL_DIR: C:\Program Files (x86)\dotnet
        with:
          dotnet-version: '8.0.x'
          architecture: x86

      - name: Show installed dotnet SDKs 
        run: |
          dotnet --list-sdks
          dotnet --info



 